[package]
name = "tenun_layout_taffy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
taffy = { version = "=0.5.1", default-features = false, features = ["flexbox", "std", "taffy_tree"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "corpus"
path = "src/main.rs"

[profile.release]
debug = true
